export const events = [
  {
    id: 1,
    title: "Next.js Conf 2026",
    description: "The ultimate event for Next.js developers. Join us for a day of learning, networking, and exciting announcements about the future of the web.",
    poster: "/images/event1.png",
    date: "2026-10-25",
    time: "09:00 AM",
    location: "San Francisco, CA",
  },
  {
    id: 2,
    title: "React Summit 2026",
    description: "A two-day conference for React enthusiasts. Experience the latest trends, best practices, and innovative solutions in the React ecosystem.",
    poster: "/images/event2.png",
    date: "2026-06-12",
    time: "10:00 AM",
    location: "Amsterdam, Netherlands",
  },
  {
    id: 3,
    title: "JSWorld Hackathon",
    description: "Unleash your creativity at the JSWorld Hackathon! Collaborate with fellow developers to build amazing projects using JavaScript and modern web technologies.",
    poster: "/images/event3.png",
    date: "2026-08-15",
    time: "08:00 AM",
    location: "Online / Global",
  },
  {
    id: 4,
    title: "TypeScript Congress",
    description: "Deep dive into the world of TypeScript. Learn about advanced type systems, performance optimizations, and building scalable applications with TS.",
    poster: "/images/event4.png",
    date: "2026-11-05",
    time: "11:00 AM",
    location: "Berlin, Germany",
  },
  {
    id: 5,
    title: "AI & Web Meetup",
    description: "Exploring the intersection of Artificial Intelligence and Web Development. Discover how AI is transforming the way we build and interact with the web.",
    poster: "/images/event5.png",
    date: "2026-05-20",
    time: "06:30 PM",
    location: "New York, NY",
  },
  {
    id: 6,
    title: "Fullstack Global 2026",
    description: "The premier conference for fullstack developers. Covering everything from frontend frameworks to backend architecture and cloud infrastructure.",
    poster: "/images/event6.png",
    date: "2026-12-01",
    time: "09:30 AM",
    location: "London, UK",
  },
];
