name: Test & Deploy Project
on:
  pull_request:
    branches:
      - main                  
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
  deploy:
    # To run jobs sequential
    # needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH="${{ github.head_ref }}"
          echo "Branch name: $BRANCH"
          if [[ ! "$BRANCH" == feature/* ]]; then
            echo "❌ Branch '$BRANCH' is not allowed. Only feature/* branches can be merged."
            exit 1
          fi
          echo "✅ Branch name is valid."
